### ISSUE TITLE
commit messages

### ISSUE THREAD

**Issue by DanielRuf** [emilwallner/Screenshot-to-code-in-Keras#11]
So far most commit messages are not very meaningful.

Can you describe what the abbreviations mean? Also longer and better commit messages are very helpful for other developers and contributors.

**Comment by emilwallner** [comment]
Solid feedback. I'm new to the open-source community - I'll keep this in mind. The abbreviations do not have any meaning.

**Comment by DanielRuf** [comment]
> Solid feedback. I'm new to the open-source community - I'll keep this in mind. The abbreviations do not have any meaning.

Ah ok. I did not know this.
