### ISSUE TITLE
Does the model do OCR?

### ISSUE THREAD

**Issue by jamespacileo** [emilwallner/Screenshot-to-code-in-Keras#13]
This project is fantastic, great learning source as well. 😄 

Does the model do OCR for the text contained in the various boxes?
Thanks

**Comment by houqp** [comment]
AFAIK, it doesn't do OCR right now.

**Comment by emilwallner** [comment]
Tldr, No. 

The main focus of the model has been on the layout, but in theory it should perform well on characters too. In the data provided, it does not include characters. 

However, you can test it on a dataset with characters. E.g. the HTML dataset and vocabulary here: https://github.com/harvardnlp/im2markup

If you are using Floydhub you can run the following command to access the data and vocab:
floyd run --gpu --env tensorflow-1.4 --data emilwallner/datasets/100k-html:data --mode jupyter
