### ISSUE TITLE
When  I run floydhub/HTML.ipynb，I encounter an problem.

### ISSUE THREAD

**Issue by GuoZgao** [emilwallner/Screenshot-to-code-in-Keras#17]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-f3c2b2b22304> in <module>()
      7 from keras.layers import Embedding, TimeDistributed, RepeatVector, LSTM, concatenate , Input, Reshape, Dense, Flatten
      8 from keras.preprocessing.image import array_to_img, img_to_array, load_img
----> 9 from keras.applications.inception_resnet_v2 import InceptionResNetV2, preprocess_input
     10 import numpy as np

ModuleNotFoundError: No module named 'keras.applications.inception_resnet_v2'

**Comment by emilwallner** [comment]
You need the Keras version 2.1.2 or later.

If you are using FloydHub, make sure you run the floyd command init and run "floyd run/init ..." inside the Screenshot-to-code-in-Keras/floydhub folder.

**Comment by Masa-Shin** [comment]
Getting same error, I ran "floyd init quick-start" and "floyd run --gpu --env tensorflow-1.4 --data emilwallner/datasets/imagetocode/1:data --mode jupyter" inside Screenshot-to-code-in-Keras folder and then run all cells of HTML.ipynb. Here what I got:

![error](https://user-images.githubusercontent.com/34234442/35361871-4e9bcc8a-01a6-11e8-87bb-ba74d2baaf82.png)

**Comment by emilwallner** [comment]
@Masa-Shin 
1) Did you run "floyd init..." inside the floydhub folder?
2) You have the wrong dataset version: "floyd run --gpu --env tensorflow-1.4 --data emilwallner/datasets/imagetocode/2:data --mode jupyter"

**Comment by Masa-Shin** [comment]
Solved. Thanks a lot!

**Comment by GuoZgao** [comment]
Thanks  you.
