### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Hzefeng** [emilwallner/Screenshot-to-code-in-Keras#18]
when I am running /floydhub/html HTML.ipynb, the first cell comes out an error

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f3c2b2b22304> in <module>()
      7 from keras.layers import Embedding, TimeDistributed, RepeatVector, LSTM, concatenate , Input, Reshape, Dense, Flatten
      8 from keras.preprocessing.image import array_to_img, img_to_array, load_img
----> 9 from keras.applications.inception_resnet_v2 import InceptionResNetV2, preprocess_input
     10 import numpy as np

ModuleNotFoundError: No module named 'keras.applications.inception_resnet_v2'

**Comment by esperancaJS** [comment]
How did you solve @Hzefeng ?

**Comment by Hzefeng** [comment]
change your dictionary to /screenshot-to-code…/Floydhub by 

cd Floydhub
