### ISSUE TITLE
I ran this project of HTML on Windows7, but output with ' <li><a <li><a <li>.....'

### ISSUE THREAD

**Issue by finallylly** [emilwallner/Screenshot-to-code-in-Keras#21]
>Environment: 
- Anaconda3-5.0.1-Windows-x86_64
- Python 3.5.4

What's the problem?
>Screenshot-to-code-in-Keras/local/HTML/HTML.ipynb

![fireshot capture 2 - html_ - http___localhost_8888_notebooks_des](https://user-images.githubusercontent.com/20592519/35670123-75474c3e-0772-11e8-827d-4d071925f190.png)

**Comment by ShiFangjun** [comment]
Use `floydhub\HTML\HTML_preloaded_weights.ipynb` and download [org-weights-epoch-0900---loss-0.0000.hdf5](https://www.floydhub.com/emilwallner/datasets/html_models/1/org-weights-epoch-0900---loss-0.0000.hdf5)

**Remenber to change the path.**

**Comment by emilwallner** [comment]
You can either use the preloaded weights like @ShiFangjun suggested, or train it until the Loss value reaches 0.0001 .

**Comment by finallylly** [comment]
I follow the steps as @ShiFangjun suggested, and then it works.

**Comment by akshayvijayan** [comment]
> Use `floydhub\HTML\HTML_preloaded_weights.ipynb` and download [org-weights-epoch-0900---loss-0.0000.hdf5](https://www.floydhub.com/emilwallner/datasets/html_models/1/org-weights-epoch-0900---loss-0.0000.hdf5)
> 
> **Remenber to change the path.**

Still not working. Showing the following error: 
ValueError: You are trying to load a weight file containing 8 layers into a model with 448 layers.
