### ISSUE TITLE
Where is example.png in the Floydhub directory

### ISSUE THREAD

**Issue by PaulGwamanda** [emilwallner/Screenshot-to-code-in-Keras#22]
In the Floydhub folder structure below, where is the example.png located that the network uses to test? In the local directory, it's under /resources as example.png but I can't find it under the Floydhub directory.  Please advise

  |-floydhub                               #Folder to run the project on Floyhub
  |  |-Bootstrap                           #The Bootstrap version
  |  |  |-compiler                         #A compiler to turn the tokens to HTML/CSS (by pix2code)

**Comment by emilwallner** [comment]
The example.png file is not used in the local version nor the Floydhub version. It's just an example of what the websites look like. All the data can be downloaded here: https://www.floydhub.com/emilwallner/datasets/imagetocode if you want the raw images you can generate a dataset from here: https://github.com/tonybeltramelli/pix2code

Hope that helps.

**Comment by PaulGwamanda** [comment]
How do you test the network against an image it's never seen to see how it performs?

**Comment by emilwallner** [comment]
You can test it on the validation images, run this file in floydhub: floydhub/Bootstrap/test_model_accuracy.ipynb

If you want to test all images:

**Change this:** for filename in (all_filenames)[-2:]:
**To this:** for filename in (all_filenames):
