### ISSUE TITLE
can i use the new picture to generate?

### ISSUE THREAD

**Issue by anna-mo** [emilwallner/Screenshot-to-code-in-Keras#23]
i upload a picture of mine in the path"./resuorce/images" 
![image](https://user-images.githubusercontent.com/26948980/38766868-f3f241ee-400a-11e8-903e-9214d3bb5151.png)

and restart kernel &run all cells ,got an result which far away from my expect, like below :
![image](https://user-images.githubusercontent.com/26948980/38766819-546fdf32-400a-11e8-8664-5f4a9c3aacf1.png)
i wonder what kind of pictures the pre-trained model contain? If it has a limited? Or something wrong with me in understanding the process of  using a new pic?

**Comment by emilwallner** [comment]
This earlier issue should answer your question: https://github.com/emilwallner/Screenshot-to-code-in-Keras/issues/20

Let me know if you need further help.
