### ISSUE TITLE
How can I use my own image?

### ISSUE THREAD

**Issue by Wisgon** [emilwallner/Screenshot-to-code-in-Keras#27]
In /local/Bootstrap/test_model_accuracy.ipynb  forth block: `train_features, texts = load_data(dir_name)`

The image data had been preprocess , it's not a raw image. I want to know how can I preprocess my raw image to the feature that can input into the model?
Can you show me the code to preprocess a raw image file? Thanks.

**Comment by emilwallner** [comment]
Yes, you can find it here: https://github.com/tonybeltramelli/pix2code/blob/master/model/classes/Utils.py
