### ISSUE TITLE
Python 2: invalid syntax

### ISSUE THREAD

**Issue by DesWurstes** [emilwallner/Screenshot-to-code-in-Keras#28]
https://github.com/emilwallner/Screenshot-to-code-in-Keras/blob/9fb9b899f5f4df9af5c3aa8dfb6b7ea667b5fe3b/local/HTML/HTML.ipynb#L175

```
  File "<ipython-input-1-2ccde9814f9a>", line 23
    print(' ' + word, end='')
                         ^
SyntaxError: invalid syntax
```

**Comment by emilwallner** [comment]
Update your python to Python 3. Feel free to make a pull request if you make it work for both python 2 & 3.
