### ISSUE TITLE
Running bootstrap.ipynb on GPU on floydhub gives MemoryError

### ISSUE THREAD

**Issue by jonoNel** [emilwallner/Screenshot-to-code-in-Keras#31]
I'm using floydhub and a GPU but when I run bootstrap.ipynb to train on dataset emilwallner/datasets/imagetocode/2:data i get an out of memory error:
Also, what is the difference between bootstrap.ipynb and bootstrap_generator.ipynb?

`---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-12-f676dabae112> in <module>()
     30     return np.array(X), np.array(y), np.array(image_data)
     31 
---> 32 X, y, image_data = preprocess_data(train_sequences, train_features)

<ipython-input-12-f676dabae112> in preprocess_data(sequences, features)
     28             X.append(in_seq[-48:])
     29             y.append(out_seq)
---> 30     return np.array(X), np.array(y), np.array(image_data)
     31 
     32 X, y, image_data = preprocess_data(train_sequences, train_features)

MemoryError: `

**Comment by emilwallner** [comment]
Bootstrap loads all the images at once, thus the memory error. If you are working on floydhub, use the bootstrap_generator, it loads data on the go.

**Comment by jonoNel** [comment]
Ok great so I should only use the bootstrap_generator? I've ran it but It does not save a models.json file where do you get this from like in your dataset?

**Comment by emilwallner** [comment]
Download them from here: https://www.floydhub.com/emilwallner/datasets/imagetocode
