### ISSUE TITLE
ValueError: Invalid bias shape: (512,)

### ISSUE THREAD

**Issue by robin0506** [emilwallner/Screenshot-to-code-in-Keras#32]
I train the model in /local/Bootstrap/bootstrap.ipynb and save the model as a hdf5 file.
Then I download the model.json from https://www.floydhub.com/emilwallner/datasets/imagetocode and change the path of modal.json and hdf5 in local/Bootstrap/test_model_accuracy.ipynb.
Finally I run the code in local/Bootstrap/test_model_accuracy.ipynb to test the accuracy.  
However, it hints ValueError: Invalid bias shape: (512,), shown as below  
I dont read the model.json line by line, but I guess the error is caused by unmatch between the json config and hdf5 file, which are expected to be matched.
Anyway, how should I correct this?  
<img width="1061" alt="wx20180827-182645 2x" src="https://user-images.githubusercontent.com/18025979/44655206-e6a74080-aa26-11e8-87af-ece7ef2ae998.png">

**Comment by emilwallner** [comment]
I don't have the full context. I'd recommend using the updated keras syntax: https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model

```
from keras.models import load_model

 # creates a HDF5 file 'my_model.h5'
model.save('my_model.h5') 
# returns a compiled model
# identical to the previous one
model = load_model('my_model.h5')
```
