### ISSUE TITLE
python version is?

### ISSUE THREAD

**Issue by lybvinci** [emilwallner/Screenshot-to-code-in-Keras#6]
which version can be used? I'm using 2.7,meet some problems!

**Comment by houqp** [comment]
You can find out the environment at: https://www.floydhub.com/emilwallner/projects/picturetocode/7. The tensorflow-1.4 environment comes with python3.6, you can read more about it from our documentation page: https://docs.floydhub.com/guides/environments/.

**Comment by lybvinci** [comment]
thanks!
