### ISSUE TITLE
Error loading weights

### ISSUE THREAD

**Issue by vshevtsova** [emilwallner/Screenshot-to-code-in-Keras#7]
I've tried to load weights, which I've downloaded from https://www.floydhub.com/emilwallner/datasets/html_models. 

In HTML.ipynb I've replaced:
``` python
# Compile the model
model = Model(inputs=[image_features, language_input], outputs=decoder_output)
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```
by
``` python
# Compile the model
model = Model(inputs=[image_features, language_input], outputs=decoder_output)
model.load_weights("org-weights-epoch-0900---loss-0.0000.hdf5")
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
```
I got error:
``` python
ValueError: You are trying to load a weight file containing 8 layers into a model with 7 layers.
```

**Comment by Narasimha1997** [comment]
Even I am facing same problem, is there any solution for this??

**Comment by emilwallner** [comment]
My bad, I uploaded the weights from an earlier model. 

I added that model here: floydhub/HTML/HTML_preloaded_weights.ipynb

You can run it on floydhub with this command: `floyd run --gpu --env tensorflow-1.4 --data emilwallner/datasets/imagetocode/2:data --data emilwallner/datasets/html_models/1:weights --mode jupyter`
