### ISSUE TITLE
Post all issues related to FloydHub here: 

### ISSUE THREAD

**Issue by danish-monu** [emilwallner/Screenshot-to-code-in-Keras#9]
i am trying to install floyd on mac:
pip install floyd-cli
fails. i tried it with sudo as well. still fails.

i m interested in development. lemme know how to set up the environment on mac

**Comment by houqp** [comment]
Hi, could you let me know what error you were getting? The easiest way to get the installation working is to install it inside a python virtualenv.

**Comment by DanielRuf** [comment]
Try the `--verbose` flag for `pip install ...`.

https://pip.pypa.io/en/stable/reference/pip/

Can you also share your macOS version?

**Comment by ReDeiPirati** [comment]
Hi @danish-monu,

As suggested by @houqp the easiest way is to use a `virtualenv`, here's the step-by-step tutorial to do it: [step-by-step-process-of-installing-floyd-cli-with-virtualenv](https://docs.floydhub.com/guides/basics/install/#step-by-step-process-of-installing-floyd-cli-with-virtualenv)

**Comment by DanielRuf** [comment]
> As suggested by @houqp the easiest way is to use a virtualenv, here's the step-by-step tutorial to do it: step-by-step-process-of-installing-floyd-cli-with-virtualenv

Would be helpful if this would be documented in the readme or if we have a Docker image for creating a Docker container with Screenshot-to-code-in-Keras and all dependencies.

**Comment by clucasalcantara** [comment]
Here, using python based on homebrew installation you could try install using `pip2 -U install floyd-cli`

**Comment by danish-monu** [comment]
thank you, i installed it using conda
